version: '3'

services:
  db:
    container_name: mysql-8.0
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass12345
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "127.0.0.1:3306:3306"
